services:
  stats-server:
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=stats-db
      - SPRING_DATASOURCE_PASSWORD=stats-db
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - stats_pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=stats-db
      - POSTGRES_PASSWORD=stats-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm-db
      - SPRING_DATASOURCE_PASSWORD=ewm-db
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    volumes:
      - ewm_pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=ewm-db
      - POSTGRES_PASSWORD=ewm-db
    healthcheck:
        test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
        interval: 5s
        timeout: 5s
        retries: 10


volumes:
  stats_pgdata:
  ewm_pgdata: